keys:
  - &users:
    - &bloodwolfe 161647C114E21F60A186E252B74857A702B0C92B
  - &hosts:
    - &angel age1zg4xs5p40rc50es7sg8c9epflm03ktxc7225kjnqydltmk26pv0sacumpa
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *angel
      - pgp:
        - *bloodwolfe
