keys:
  - &users:
    - &bloodwolfe 161647C114E21F60A186E252B74857A702B0C92B
  - &hosts:
    #- &lapis age1y5qefq3v2mn8dqlvq2rw0ysmmn0fh3sp6rdmxw0c8r4ndvnfyvssn99k4w
    - &angel age1e5t5a5py5clu7yalcks3hyc5rcmdwelkeerprct30d4gywwclpeqnmft9u
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        #- *lapis
        - *angel
      - pgp:
        - *bloodwolfe
