keys:
  - &users:
    - &bloodwolfe 161647C114E21F60A186E252B74857A702B0C92B
  - &hosts:
    - &lapis age13xnylc88zkscls5xyvryg3t8uarc7tezcr6xhmmpwgm2clhns3nqfhpsas
    - &angel age15nju2qyyen8clwxsr0jgnnjxv9z8c0gyqdngcl2aj65r5xt5cpequxu86j   
creation_rules:
  - path_regex: secrets/.*
    key_groups:
      - pgp:
        - *bloodwolfe
        age:
        - *lapis
        - *angel
