client_id = "d420a117a32841c2b3474932e49fb54b"
client_port = 8080
login_redirect_uri = "http://127.0.0.1:8989/login"
default_player = "daemon-player"

[device]
name = "daemon-player"
device_type = "speaker"
volume = 70
bitrate = 320
audio_cache = false
normalization = false
autoplay = false
