[global]
device_name = "daemon-player"
device_type = "speaker"
#cache_path = "/full/path/to/cache/directory"
#no_audio_cache = true
#max_cache_size = 1000000000
use_mpris = true
dbus_type = "session"
#disable_discovery = false
#zeroconf_port = 1234
backend = "pulseaudio"
device = "default"
#audio_format = "S16"
volume_controller = "softvol"
control = "default"
mixer = "PCM"
bitrate = 320
initial_volume = 70
volume_normalisation = false
#normalisation_pregain = -10
autoplay = false
#on_song_change_hook = "echo \"hook executed on $PLAYER_EVENT\""
#proxy = "http://proxy.example.org:8080"
