config-version = "2.7"
bind = "0.0.0.0:25577"
motd = "<#09add3>never knows best"
show-max-players = 100

online-mode = true
force-key-authentication = false
prevent-client-proxy-connections = false
player-info-forwarding-mode = "modern"
forwarding-secret-file = "forwarding.secret"
announce-forge = true
kick-existing-players = false
ping-passthrough = "DISABLED"
enable-player-address-logging = true

[servers]
hub-mc = "hub-mc-hub-mc-1:25565"
yuis-mc = "modded-mc-modded-mc-1:25565"
vanilla-mc = "vanilla-mc-vanilla-mc-1:25565"
creative-mc = "creative-mc-creative-mc-1:25565"
pixelmon-mc = "pixelmon-mc-pixelmon-mc-1:25565"
xyz-mc = "xyz-mc-xyz-mc-1:25565"
#vanilla-mc-hard = "vanilla-mc-hard-vanilla-mc-hard:25565"

try = [
    "hub-mc",
    "vanilla-mc",
    "pixelmon-mc"
]

[forced-hosts]
"localhost" = [
  "hub-mc"
]

[advanced]
compression-threshold = 256
compression-level = -1
login-ratelimit = 3000
connection-timeout = 5000
read-timeout = 30000
haproxy-protocol = false
tcp-fast-open = false
bungee-plugin-message-channel = true
show-ping-requests = false
failover-on-unexpected-server-disconnect = true
announce-proxy-commands = true
log-command-executions = false
log-player-connections = true
accepts-transfers = false

[query]
enabled = false
port = 25577
map = "Velocity"
show-plugins = false
